import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopBar from "@/ui/TopBar";
import { DialogProvider } from "@/ui/DialogProvider";
import { getSessionUser } from "@/util/auth";
import ClientApp from "@/ui/users/ClientApp";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getSessionUser();
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="w-full border-b">
          <link
            rel="stylesheet"
            href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/static/pretendard.css"
          />
          <div className="mx-auto w-full max-w-[1200px] px-6">
            <TopBar />
          </div>
        </header>
        <ClientApp initialUser={user}/>
        <DialogProvider />
        <main className="mx-auto w-full max-w-[1200px] px-6 py-8">{children}</main>
      </body>
    </html>
  );
}
